-- Migration: Expanded knowledge base covering all peripherals and common connections
-- Fills gaps in CAN, USB, GPIO patterns, pin remapping, DMA, timers, and many device categories

INSERT OR IGNORE INTO knowledge (id, topic, keywords, content) VALUES

-- ========== CAN Bus ==========
('can_generic_connection', 'CAN', 'can bus connect wire transceiver mcp2551 sn65hvd230 tja1050 obd2 automotive vehicle',
'CAN bus connection guide for STM32F103C8T6: The CAN controller needs an external transceiver (the chip only has the protocol logic, not the physical layer). Common transceivers: MCP2551 (5V), SN65HVD230 (3.3V, recommended), TJA1050 (5V). Wiring: STM32 PA11 (CAN_RX) to transceiver RXD, PA12 (CAN_TX) to transceiver TXD. Can remap to PB8 (RX) / PB9 (TX). The bus needs 120 ohm termination resistors at each end. CAN uses two differential wires: CANH and CANL. IMPORTANT: CAN shares PA11/PA12 with USB — you cannot use both simultaneously. Supports speeds up to 1Mbit/s. Common baud rates: 125k, 250k, 500k (automotive), 1M.'),

-- ========== USB ==========
('usb_generic_connection', 'USB', 'usb connect wire device hid cdc serial keyboard mouse mass storage dfu bootloader',
'USB connection guide for STM32F103C8T6: USB pins are PA11 (D-) and PA12 (D+). The Blue Pill board typically has a USB connector already wired. For custom boards: D+ needs a 1.5k pull-up resistor to 3.3V (signals device presence to host). USB is Full-Speed (12Mbit/s). Common USB classes: CDC (virtual serial port — easiest, appears as COM port), HID (keyboard/mouse/gamepad, no driver needed), MSC (mass storage). IMPORTANT: USB shares PA11/PA12 with CAN — cannot use both. The 48MHz USB clock must be derived from PLL (use 8MHz HSE crystal for accurate timing). Blue Pill boards often have wrong pull-up resistor value (10k instead of 1.5k) — may need hardware mod. DFU bootloader mode: set BOOT0=1, reset, flash via USB with dfu-util.'),

-- ========== GPIO Practical Patterns ==========
('gpio_output_patterns', 'GPIO', 'gpio output led relay buzzer solenoid mosfet transistor driver high low',
'GPIO output patterns for STM32F103C8T6: LEDs: connect anode to GPIO through 220-330 ohm resistor to GND (active high), or cathode to GPIO with anode to 3.3V (active low). Max 8mA recommended per pin, 25mA absolute max. For loads over 25mA: use an NPN transistor (2N2222) or N-channel MOSFET (2N7000, IRLZ44N) as a switch — GPIO drives the gate/base, load connects to drain/collector with external power. Relays: use a transistor driver + flyback diode (1N4148), or buy a relay module with built-in driver. Buzzers: passive buzzers need PWM (use timer pin), active buzzers just need GPIO HIGH. Solenoids: always use a MOSFET/transistor + flyback diode. Any GPIO pin works for output.'),

('gpio_input_patterns', 'GPIO', 'gpio input button switch sensor debounce pull-up pull-down digital read',
'GPIO input patterns for STM32F103C8T6: Buttons/switches: connect between GPIO pin and GND, enable internal pull-up in software (reads HIGH when open, LOW when pressed). Or use external 10k pull-up/pull-down resistor. Debouncing: software delay (10-50ms after edge detected) or hardware RC filter (10k + 100nF). For interrupt-driven buttons: configure EXTI on the pin, use falling edge trigger with pull-up. Digital sensors (PIR, tilt, vibration, reed switch): same pattern as buttons. Optical encoders: use timer encoder mode for hardware counting. Limit switches: pull-up + active low like buttons. IMPORTANT: for 5V digital signals, use 5V-tolerant pins (PA8-PA15, PB2-PB4, PB6-PB15).'),

-- ========== Pin Remapping ==========
('pin_remapping_guide', 'GPIO', 'remap afio alternate function pin reassign move change peripheral different pins',
'Pin remapping guide for STM32F103C8T6: Many peripherals can be remapped to alternate pins using the AFIO (Alternate Function I/O) peripheral. You must enable AFIO clock first (RCC_APB2ENR). Remappable peripherals: USART1 (PA9/PA10 -> PB6/PB7), I2C1 (PB6/PB7 -> PB8/PB9), SPI1 (PA4-PA7 -> PA15/PB3-PB5), CAN (PA11/PA12 -> PB8/PB9), TIM1-TIM4 (various remaps). IMPORTANT: USART1 remap to PB6/PB7 conflicts with I2C1 default pins. I2C1 remap to PB8/PB9 frees PB6/PB7 for USART1. JTAG pins (PA13/PA14/PA15/PB3/PB4) can be partially or fully released for GPIO use via AFIO_MAPR register — partial release frees PA15/PB3/PB4, full release also frees PA13/PA14 (loses JTAG, keeps SWD on PA13/PA14 with partial).'),

-- ========== DMA Practical ==========
('dma_practical_guide', 'DMA', 'dma direct memory access adc uart spi transfer fast efficient buffer circular',
'DMA practical usage guide for STM32F103C8T6: DMA1 has 7 channels, each dedicated to specific peripherals. Common uses: ADC+DMA: continuously sample ADC channels into a buffer without CPU intervention — essential for multi-channel or high-speed sampling. Set ADC to scan mode + continuous, DMA to circular mode. UART+DMA: transmit large buffers without blocking (DMA1_CH4 for USART1_TX, CH5 for USART1_RX). Receive unknown-length data using IDLE line detection + DMA. SPI+DMA: fast display updates or SD card transfers (DMA1_CH3 for SPI1_TX, CH2 for SPI1_RX). Memory-to-memory: copy large arrays quickly. Channel assignments are fixed in hardware — check reference manual Table 78 for channel-to-peripheral mapping. Priority levels: Very High, High, Medium, Low.'),

-- ========== Timer Advanced ==========
('timer_input_capture', 'Timer', 'timer input capture frequency measurement pulse width echo encoder counter',
'Timer input capture guide for STM32F103C8T6: Input capture measures the timing of external signals. Uses: frequency measurement, pulse width measurement (HC-SR04 echo), RPM counting, period measurement. Configure timer channel as input capture, trigger on rising/falling/both edges. The timer counter value is captured on each edge. For HC-SR04: trigger pin = any GPIO output (10us pulse), echo pin = timer input capture channel. Measure time between rising and falling edge of echo. Timer pins: TIM1 CH1-CH4 (PA8-PA11), TIM2 CH1-CH4 (PA0-PA3), TIM3 CH1-CH2 (PA6-PA7), TIM3 CH3-CH4 (PB0-PB1), TIM4 CH1-CH4 (PB6-PB9). Encoder mode: TIM1-TIM4 can count quadrature encoder pulses in hardware using CH1+CH2 — no CPU overhead, handles both direction and position.'),

('timer_advanced_features', 'Timer', 'timer complementary dead time brake center aligned repetition advanced tim1',
'Advanced timer features (TIM1) on STM32F103C8T6: TIM1 is the advanced-control timer with features for motor control. Complementary outputs: CH1/CH1N, CH2/CH2N, CH3/CH3N — generates complementary PWM pairs for H-bridge driving. Dead-time insertion: prevents shoot-through in half-bridge circuits by adding a gap between complementary signals. Break input (BKIN on PB12): emergency shutdown — immediately disables all outputs (for overcurrent protection). Center-aligned PWM: counts up then down for symmetric PWM waveforms (reduces harmonics in motor control). Repetition counter: generate update events every N overflow cycles. TIM1 channels: PA8 (CH1), PA9 (CH2), PA10 (CH3), PA11 (CH4). Complementary: PB13 (CH1N), PB14 (CH2N), PB15 (CH3N).'),

-- ========== Motor Drivers ==========
('motor_driver_modules', 'Sensors', 'motor driver h-bridge l298n drv8833 tb6612 l293d a4988 drv8825 stepper dc brushed',
'Motor driver modules for STM32F103C8T6: DC motors: L298N (dual H-bridge, 2A per channel, needs 7-12V supply, ENA/ENB for PWM speed control + IN1-IN4 for direction — 6 GPIO pins total). DRV8833 (dual, 1.5A, 2.7-10.8V, simpler — just 4 PWM pins). TB6612FNG (dual, 1.2A, best efficiency — PWMA/PWMB + AIN1/AIN2/BIN1/BIN2 + STBY). L293D (dual, 600mA, DIP package for breadboards). Stepper motors: A4988 (up to 2A, needs STEP + DIR pins, microstepping via MS1/MS2/MS3). DRV8825 (up to 2.5A, same pinout as A4988, 32 microsteps). TMC2209 (silent, UART config, STEP+DIR). For all drivers: connect motor power supply separately (NOT from STM32 3.3V), share GND with STM32, connect STEP/DIR/PWM/IN pins to any GPIO.'),

('stepper_motor_connection', 'Sensors', 'stepper motor nema17 nema23 28byj bipolar unipolar a4988 uln2003 steps rotation position',
'Stepper motor connection guide for STM32F103C8T6: Bipolar steppers (NEMA17, 4 wires): use A4988 or DRV8825 driver. Wiring: STEP pin to any GPIO (or timer for precise timing), DIR to any GPIO, ENABLE to any GPIO (active low). Power: VMOT to 12V supply, GND shared with STM32. Set current limit with driver potentiometer. Microstepping: MS1/MS2/MS3 to GPIO or tie high/low. Unipolar steppers (28BYJ-48, 5 wires): use ULN2003 driver board. Connect IN1-IN4 to 4 GPIO pins, power the ULN2003 from 5V. Drive in half-step or full-step sequence in software. For precise positioning: use timer interrupts for consistent step timing. Speed control: vary the timer frequency. Acceleration: ramp the step rate up/down gradually.'),

-- ========== Distance Sensors ==========
('distance_sensors_general', 'Sensors', 'distance sensor hcsr04 ultrasonic vl53l0x vl53l1x tof lidar ir sharp range proximity',
'Distance sensor connection guide for STM32F103C8T6: HC-SR04 ultrasonic (2-400cm): TRIG to any GPIO (10us pulse), ECHO to 5V-tolerant pin (use PA8-PA15 or PB6-PB15) or voltage divider. VCC=5V. Measure echo pulse width with timer input capture or GPIO polling. VL53L0X/VL53L1X ToF laser (up to 2m/4m): I2C (0x29 default), connect to PB6/PB7, 3.3V compatible, very accurate. VL53L4CD/VL53L5CX: same I2C bus, multi-zone. Sharp GP2Y0A21 IR analog (10-80cm): analog voltage output to ADC pin (PA0-PA7), NOT 5V tolerant so check sensor output range. TF-Luna/TFMini LiDAR (0.1-12m): UART at 115200 baud (PA9/PA10) or I2C. For multiple ultrasonic sensors: use one TRIG but separate ECHO pins, or multiplex with GPIO.'),

-- ========== Current/Power Sensors ==========
('current_sensors_general', 'Sensors', 'current sensor ina219 ina226 acs712 acs758 voltage measurement power monitor shunt',
'Current and power sensor guide for STM32F103C8T6: INA219 (I2C, 0x40-0x4F): high-side current + voltage + power measurement, 26V max, configurable shunt resistor. Connect to PB6/PB7 I2C bus. Very accurate, 12-bit. INA226: similar but 36V max and 16-bit. ACS712 (analog output): Hall-effect current sensor, 5A/20A/30A versions, outputs analog voltage centered at VCC/2 (2.5V at 0A). Connect output to ADC pin — output may exceed 3.3V, use a voltage divider. Needs 5V VCC. ACS758: higher current version (50A-200A), same concept. For simple voltage measurement: use a resistor divider to bring voltage below 3.3V, connect to ADC pin. Example: 2x 10k dividers halve the voltage (max 6.6V input). For battery monitoring: INA219 is best (gives voltage, current, and power over I2C).'),

-- ========== EEPROM/Flash Storage ==========
('eeprom_storage_modules', 'Sensors', 'eeprom storage memory at24c32 at24c64 at24c256 w25q flash save data persistent non-volatile',
'External storage modules for STM32F103C8T6: I2C EEPROM: AT24C32 (4KB), AT24C64 (8KB), AT24C256 (32KB). Address: 0x50-0x57 (set by A0-A2 pins). Connect to PB6/PB7 I2C bus. Write is slow (~5ms per page) but reads are fast. Good for config storage, calibration data, small logs. Often bundled with DS3231 RTC modules. SPI Flash: W25Q32 (4MB), W25Q64 (8MB), W25Q128 (16MB). Connect to SPI1 (PA5-PA7 + CS on any GPIO). Much faster than EEPROM, good for data logging, audio storage. Sector erase required before write (4KB sectors). Internal flash: STM32F103C8T6 has 64KB, you can use the last few pages for persistent storage — but be careful with wear leveling and write during execution. SD card via SPI is best for large data logging.'),

-- ========== RTC Modules ==========
('rtc_modules_general', 'Sensors', 'rtc real time clock ds3231 ds1307 pcf8563 time date calendar battery backup alarm',
'RTC module connection guide for STM32F103C8T6: DS3231 (recommended): I2C (0x68), extremely accurate (+/-2ppm), built-in temperature compensation, battery backup (CR2032), alarm functions, 32KHz output. Connect SDA/SCL to PB6/PB7. NOTE: address 0x68 conflicts with MPU6050 — use AD0 pin on MPU6050 to change its address to 0x69 if using both. DS1307: I2C (0x68), needs external 32.768kHz crystal, less accurate than DS3231, battery backup. Cheaper but drifts more. PCF8563: I2C (0x51), low power, different address so no conflicts. Internal RTC: STM32F103C8T6 has a built-in RTC that can use a 32.768kHz LSE crystal (on PC14/PC15) with VBAT battery backup. The internal RTC is a seconds counter only — you must convert to/from calendar in software. External modules give you calendar format directly.'),

-- ========== Camera Modules ==========
('camera_modules_general', 'Sensors', 'camera ov7670 ov2640 arducam image capture photo video vision',
'Camera module guide for STM32F103C8T6: OV7670 (no FIFO): 640x480 VGA, parallel interface needing 8 data pins + VSYNC + HREF + PCLK + XCLK + I2C (SCCB). This uses ~12 GPIO pins and requires precise timing. VERY challenging on STM32F103C8T6 due to limited RAM (20KB — one VGA frame is 614KB). Practical approach: capture at QQVGA (160x120) or use OV7670 with FIFO buffer (AL422B). OV2640: 2MP, similar parallel interface, often with FIFO. ArduCAM Mini: SPI interface + I2C for config — much easier to use, only needs SPI1 + I2C1 + CS pin. IMPORTANT: the STM32F103C8T6 is not ideal for camera applications due to RAM limitations. Consider STM32F4 series for serious image processing. For simple image capture and transfer via UART, ArduCAM Mini with SPI is the practical choice.'),

-- ========== Interrupt Practical Guide ==========
('interrupts_practical', 'Interrupts', 'interrupt exti handler callback isr priority nested button timer uart dma',
'Practical interrupt guide for STM32F103C8T6: External interrupts (EXTI): any GPIO can trigger an interrupt on rising/falling/both edges. EXTI lines 0-4 have individual handlers, 5-9 share one handler, 10-15 share another. Use for buttons, sensor alerts, data-ready signals. Timer interrupts: update interrupt fires on overflow/underflow — use for periodic tasks (sensor polling, LED blinking, control loops). UART RX interrupt: fires on each received byte — use for receiving serial data without polling. DMA transfer complete interrupt: fires when DMA finishes a block transfer. Priorities: 0 (highest) to 15 (lowest), 4 bits configurable. Nested interrupts: higher priority can preempt lower priority handlers. Keep ISRs short — set a flag and process in main loop. Volatile keyword required for variables shared between ISR and main code.'),

-- ========== Watchdog Practical ==========
('watchdog_practical', 'Watchdog', 'watchdog iwdg wwdg reset hang crash recover timeout reliable',
'Watchdog practical guide for STM32F103C8T6: Use the Independent Watchdog (IWDG) to automatically reset the MCU if your code hangs. Setup: enable IWDG, set prescaler and reload value to define timeout (e.g., prescaler=64, reload=625 gives ~1 second timeout). Call IWDG refresh (kick the dog) regularly in your main loop. If the code crashes, hangs in an infinite loop, or gets stuck waiting for a peripheral — the watchdog will reset the MCU. Window Watchdog (WWDG) is more precise — must be refreshed within a specific time window, not just before timeout. Useful for detecting timing errors. Common pattern: initialize IWDG with 2-4 second timeout, refresh at the top of your main while loop. For multi-task systems: each task sets a flag, watchdog refresh only if all flags are set.'),

-- ========== DAC (chip doesn't have one) ==========
('dac_alternatives', 'ADC', 'dac digital analog output convert voltage signal waveform no dac mcp4725 pwm filter',
'DAC alternatives for STM32F103C8T6: This chip does NOT have a built-in DAC (the STM32F103RB and higher do). Alternatives: PWM + RC filter: generate PWM on a timer pin, filter with an RC low-pass (e.g., 10k + 100nF for ~160Hz cutoff). Gives a pseudo-analog output good enough for LED dimming, simple audio, or slow control signals. Higher PWM frequency = smoother output. External DAC: MCP4725 (12-bit, I2C, 0x60-0x63) — single channel, easy to use, connect to PB6/PB7. MCP4728 (4-channel, I2C). MCP4922 (12-bit, dual, SPI). For audio: use I2S or SPI DAC like PCM5102 or MAX98357. R-2R resistor ladder: connect 8 GPIO pins through a resistor network for a quick 8-bit DAC (lower quality but no extra chip needed).'),

-- ========== Debugging and Programming ==========
('debug_programming_guide', 'Development', 'debug program flash stlink swd jtag serial wire openocd gdb upload bootloader',
'Programming and debugging guide for STM32F103C8T6: SWD (Serial Wire Debug) is the primary debug interface — only needs 2 pins: SWDIO (PA13) and SWCLK (PA14), plus GND and optionally 3.3V. Use an ST-Link V2 programmer (cheap clones work fine). Connect: SWDIO to PA13, SWCLK to PA14, GND to GND, 3.3V to 3.3V (optional, powers the board). Flash via STM32CubeProgrammer, OpenOCD, or directly from your IDE. For debugging: use OpenOCD + GDB, or STM32CubeIDE built-in debugger — set breakpoints, inspect variables, step through code. Serial bootloader: built into ROM, activated by BOOT0=1 + reset. Flash via UART1 (PA9/PA10) using stm32flash tool. USB DFU: some bootloaders support USB flashing. IMPORTANT: do not reassign PA13/PA14 as GPIO unless you have another way to reflash (serial bootloader).'),

-- ========== Common Project Patterns ==========
('project_data_logger', 'Development', 'data logger logging sd card csv sensor record save timestamp project example',
'Data logger project pattern for STM32F103C8T6: Components: sensor(s) on I2C/SPI/ADC + SD card on SPI + optional DS3231 RTC for timestamps. Wiring: sensors on I2C1 (PB6/PB7), SD card on SPI1 (PA5-PA7, CS on PA4), RTC on same I2C bus (if different address). Flow: initialize all peripherals, create/open CSV file on SD, in main loop: read sensor, format as CSV line with timestamp, write to SD, delay or use timer for sampling interval. Use DMA for ADC if sampling multiple analog channels. Flush SD write buffer periodically to prevent data loss on power failure. Power: for battery operation, use sleep mode between samples, wake via RTC alarm or timer. Typical sample rates: 1Hz for environmental, 100Hz+ for motion/vibration (use DMA + timer).'),

('project_motor_control', 'Development', 'robot motor control pid encoder feedback speed position servo project',
'Motor control project pattern for STM32F103C8T6: DC motor with feedback: motor through H-bridge (L298N/DRV8833) connected to timer PWM pin + 2 direction GPIO pins. Encoder on timer in encoder mode (hardware counting). PID loop in timer interrupt (100Hz-1kHz): read encoder count, compute error, adjust PWM duty cycle. Servo robot: up to ~6 servos on timer PWM pins (50Hz, 1-2ms pulse). More servos: use PCA9685 I2C servo driver (0x40, controls 16 servos). Stepper positioning: A4988 driver, STEP pin on timer output for precise frequency control, acceleration ramp in software. Always use separate motor power supply, share GND with STM32. Add decoupling capacitors near motor driver. For wireless control: add HC-05 Bluetooth or NRF24L01.');

-- Also add to device_patterns for modules not yet covered
INSERT OR IGNORE INTO device_patterns (id, device_name, device_type, interface_type, default_pins, requirements, notes, keywords) VALUES
('ina219', 'INA219', 'Current/Power Sensor', 'I2C', '{"SCL": "PB6", "SDA": "PB7"}', '4.7k pull-up resistors', 'I2C address: 0x40-0x4F (configurable via A0/A1). Measures current, voltage, and power. 26V max bus voltage.', 'INA219 current power voltage sensor monitor I2C'),
('vl53l0x', 'VL53L0X', 'Time-of-Flight Distance Sensor', 'I2C', '{"SCL": "PB6", "SDA": "PB7"}', '4.7k pull-up resistors', 'I2C address: 0x29. Laser ranging up to 2m. 3.3V compatible. XSHUT pin for address reassignment with multiple sensors.', 'VL53L0X ToF distance laser range proximity I2C'),
('hcsr04', 'HC-SR04', 'Ultrasonic Distance Sensor', 'GPIO', '{"TRIG": "PA1", "ECHO": "PA8"}', 'Voltage divider on ECHO if using non-5V-tolerant pin', '5V sensor. ECHO pin outputs 5V — use 5V-tolerant pin or voltage divider. Range: 2-400cm.', 'HC-SR04 HCSR04 ultrasonic distance sonar range'),
('dht22', 'DHT22', 'Temperature/Humidity Sensor', 'GPIO', '{"DATA": "PA0"}', '10k pull-up resistor on data line', 'Single-wire protocol. Range: -40-80C, 0-100% RH. 3.3V or 5V compatible. Reads every 2 seconds max.', 'DHT22 AM2302 temperature humidity digital'),
('ws2812b', 'WS2812B', 'Addressable LED Strip', 'GPIO', '{"DATA": "PA0"}', '330-470 ohm resistor on data line, 1000uF capacitor on power', '5V LEDs but data line accepts 3.3V from most STM32 pins. Use timer DMA for precise timing. 60mA per LED at full white.', 'WS2812B WS2812 neopixel addressable LED RGB strip'),
('a4988', 'A4988', 'Stepper Motor Driver', 'GPIO', '{"STEP": "PA0", "DIR": "PA1", "ENABLE": "PA2"}', 'Separate motor power supply 8-35V', 'Connect STEP to timer pin for precise frequency control. MS1/MS2/MS3 for microstepping. Current limit set by potentiometer.', 'A4988 stepper motor driver NEMA step direction'),
('mcp4725', 'MCP4725', 'DAC (Digital-to-Analog Converter)', 'I2C', '{"SCL": "PB6", "SDA": "PB7"}', '4.7k pull-up resistors', 'I2C address: 0x60 or 0x62. 12-bit single channel DAC. Output 0-3.3V. STM32F103C8T6 has no built-in DAC — use this module.', 'MCP4725 DAC digital analog converter output voltage I2C'),
('pca9685', 'PCA9685', 'PWM/Servo Driver', 'I2C', '{"SCL": "PB6", "SDA": "PB7"}', '4.7k pull-up resistors, external power for servos', 'I2C address: 0x40-0x7F (configurable). 16 PWM channels at 12-bit resolution. Ideal for controlling many servos or LEDs. Separate V+ power for servos.', 'PCA9685 PWM servo driver 16 channel I2C'),
('ads1115', 'ADS1115', 'ADC (16-bit External)', 'I2C', '{"SCL": "PB6", "SDA": "PB7"}', '4.7k pull-up resistors', 'I2C address: 0x48-0x4B. 16-bit 4-channel ADC with programmable gain. Much higher resolution than the built-in 12-bit ADC. Good for precision measurements.', 'ADS1115 ADS1015 ADC analog digital converter 16-bit precision I2C'),
('ssd1306_spi', 'SSD1306 SPI OLED', 'Display', 'SPI', '{"SCK": "PA5", "MOSI": "PA7", "CS": "PA4", "DC": "PA3", "RST": "PA2"}', 'None', 'SPI OLED is faster than I2C version. DC pin selects data/command. RST pin for hardware reset. No MISO needed (display only). 0.96" or 1.3" common sizes.', 'SSD1306 OLED display SPI screen'),
('ili9341', 'ILI9341', 'TFT Display (2.4"+)', 'SPI', '{"SCK": "PA5", "MISO": "PA6", "MOSI": "PA7", "CS": "PA4", "DC": "PA3", "RST": "PA2"}', 'None', 'SPI TFT color display. 240x320 resolution. Use DMA for fast updates. Some modules include touch screen (XPT2046 on separate SPI CS). LED backlight pin needs 3.3V.', 'ILI9341 TFT LCD display color screen SPI touch');
